<?php /* Smarty version 2.6.11, created on 2014-09-19 09:41:30
         compiled from article/article_text.html */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'cat', 'article/article_text.html', 1, false),array('modifier', 'date_format', 'article/article_text.html', 3, false),array('modifier', 'strip', 'article/article_text.html', 4, false),)), $this); ?>
Article title: <?php echo ((is_array($_tmp=$this->_tpl_vars['article_info']['title'])) ? $this->_run_mod_handler('cat', true, $_tmp, "\r\n") : smarty_modifier_cat($_tmp, "\r\n")); ?>

Keyword: <?php echo ((is_array($_tmp=$this->_tpl_vars['article_info']['keyword'])) ? $this->_run_mod_handler('cat', true, $_tmp, "\r\n") : smarty_modifier_cat($_tmp, "\r\n")); ?>

Submit Date: <?php if ($this->_tpl_vars['article_info']['article_status'] == '0' || $this->_tpl_vars['article_info']['article_status'] == ''): ?>n/a<?php else:  echo ((is_array($_tmp=((is_array($_tmp=$this->_tpl_vars['article_info']['cp_updated'])) ? $this->_run_mod_handler('date_format', true, $_tmp, "%m-%d-%Y") : smarty_modifier_date_format($_tmp, "%m-%d-%Y")))) ? $this->_run_mod_handler('cat', true, $_tmp, "\r\n") : smarty_modifier_cat($_tmp, "\r\n"));  endif; ?>
<?php if (((is_array($_tmp=$this->_tpl_vars['article_info']['tags'])) ? $this->_run_mod_handler('strip', true, $_tmp) : smarty_modifier_strip($_tmp)) != ''): ?>Tags: <?php echo ((is_array($_tmp=$this->_tpl_vars['article_info']['tags'])) ? $this->_run_mod_handler('cat', true, $_tmp, "\r\n") : smarty_modifier_cat($_tmp, "\r\n"));  endif; ?>
<?php if (((is_array($_tmp=$this->_tpl_vars['article_info']['mapping_id'])) ? $this->_run_mod_handler('strip', true, $_tmp) : smarty_modifier_strip($_tmp)) != ''): ?>Mapping-ID: <?php echo ((is_array($_tmp=$this->_tpl_vars['article_info']['mapping_id'])) ? $this->_run_mod_handler('cat', true, $_tmp, "\r\n") : smarty_modifier_cat($_tmp, "\r\n"));  endif; ?>
<?php if (((is_array($_tmp=$this->_tpl_vars['article_info']['optional1'])) ? $this->_run_mod_handler('strip', true, $_tmp) : smarty_modifier_strip($_tmp)) != ''): ?>Optional Field 1: <?php echo ((is_array($_tmp=$this->_tpl_vars['article_info']['optional1'])) ? $this->_run_mod_handler('cat', true, $_tmp, "\r\n") : smarty_modifier_cat($_tmp, "\r\n"));  endif; ?>
<?php if (((is_array($_tmp=$this->_tpl_vars['article_info']['optional2'])) ? $this->_run_mod_handler('strip', true, $_tmp) : smarty_modifier_strip($_tmp)) != ''): ?>Optional Field 2: <?php echo ((is_array($_tmp=$this->_tpl_vars['article_info']['optional2'])) ? $this->_run_mod_handler('cat', true, $_tmp, "\r\n") : smarty_modifier_cat($_tmp, "\r\n"));  endif; ?>
<?php if (((is_array($_tmp=$this->_tpl_vars['article_info']['optional3'])) ? $this->_run_mod_handler('strip', true, $_tmp) : smarty_modifier_strip($_tmp)) != ''): ?>Optional Field 3: <?php echo ((is_array($_tmp=$this->_tpl_vars['article_info']['optional3'])) ? $this->_run_mod_handler('cat', true, $_tmp, "\r\n") : smarty_modifier_cat($_tmp, "\r\n"));  endif; ?>
<?php if (((is_array($_tmp=$this->_tpl_vars['article_info']['optional4'])) ? $this->_run_mod_handler('strip', true, $_tmp) : smarty_modifier_strip($_tmp)) != ''): ?>Optional Field 4: <?php echo ((is_array($_tmp=$this->_tpl_vars['article_info']['optional4'])) ? $this->_run_mod_handler('cat', true, $_tmp, "\r\n") : smarty_modifier_cat($_tmp, "\r\n"));  endif; ?>
<?php if (((is_array($_tmp=$this->_tpl_vars['article_info']['optional5'])) ? $this->_run_mod_handler('strip', true, $_tmp) : smarty_modifier_strip($_tmp)) != ''): ?>Optional Field 5: <?php echo ((is_array($_tmp=$this->_tpl_vars['article_info']['optional5'])) ? $this->_run_mod_handler('cat', true, $_tmp, "\r\n") : smarty_modifier_cat($_tmp, "\r\n"));  endif; ?>
<?php if (((is_array($_tmp=$this->_tpl_vars['article_info']['optional6'])) ? $this->_run_mod_handler('strip', true, $_tmp) : smarty_modifier_strip($_tmp)) != ''): ?>Optional Field 6: <?php echo ((is_array($_tmp=$this->_tpl_vars['article_info']['optional6'])) ? $this->_run_mod_handler('cat', true, $_tmp, "\r\n") : smarty_modifier_cat($_tmp, "\r\n"));  endif; ?>
<?php if (((is_array($_tmp=$this->_tpl_vars['article_info']['optional7'])) ? $this->_run_mod_handler('strip', true, $_tmp) : smarty_modifier_strip($_tmp)) != ''): ?>Optional Field 7: <?php echo ((is_array($_tmp=$this->_tpl_vars['article_info']['optional7'])) ? $this->_run_mod_handler('cat', true, $_tmp, "\r\n") : smarty_modifier_cat($_tmp, "\r\n"));  endif; ?>
<?php if (((is_array($_tmp=$this->_tpl_vars['article_info']['optional8'])) ? $this->_run_mod_handler('strip', true, $_tmp) : smarty_modifier_strip($_tmp)) != ''): ?>Optional Field 8: <?php echo ((is_array($_tmp=$this->_tpl_vars['article_info']['optional8'])) ? $this->_run_mod_handler('cat', true, $_tmp, "\r\n") : smarty_modifier_cat($_tmp, "\r\n"));  endif; ?>
<?php if (((is_array($_tmp=$this->_tpl_vars['article_info']['optional9'])) ? $this->_run_mod_handler('strip', true, $_tmp) : smarty_modifier_strip($_tmp)) != ''): ?>Optional Field 9: <?php echo ((is_array($_tmp=$this->_tpl_vars['article_info']['optional9'])) ? $this->_run_mod_handler('cat', true, $_tmp, "\r\n") : smarty_modifier_cat($_tmp, "\r\n"));  endif; ?>
<?php if (((is_array($_tmp=$this->_tpl_vars['article_info']['optional10'])) ? $this->_run_mod_handler('strip', true, $_tmp) : smarty_modifier_strip($_tmp)) != ''): ?>Optional Field 10: <?php echo ((is_array($_tmp=$this->_tpl_vars['article_info']['optional10'])) ? $this->_run_mod_handler('cat', true, $_tmp, "\r\n") : smarty_modifier_cat($_tmp, "\r\n"));  endif; ?>
<?php if ($this->_tpl_vars['article_info']['template'] == '2'): ?>
<?php if (((is_array($_tmp=$this->_tpl_vars['article_info']['small_image'])) ? $this->_run_mod_handler('strip', true, $_tmp) : smarty_modifier_strip($_tmp)) != ''): ?>Small Image: <?php echo ((is_array($_tmp=$this->_tpl_vars['article_info']['small_image'])) ? $this->_run_mod_handler('cat', true, $_tmp, "\r\n") : smarty_modifier_cat($_tmp, "\r\n"));  endif; ?>
<?php if (((is_array($_tmp=$this->_tpl_vars['article_info']['large_image'])) ? $this->_run_mod_handler('strip', true, $_tmp) : smarty_modifier_strip($_tmp)) != ''): ?>Large Image: <?php echo ((is_array($_tmp=$this->_tpl_vars['article_info']['large_image'])) ? $this->_run_mod_handler('cat', true, $_tmp, "\r\n") : smarty_modifier_cat($_tmp, "\r\n"));  endif; ?>
<?php if (((is_array($_tmp=$this->_tpl_vars['article_info']['image_credit'])) ? $this->_run_mod_handler('strip', true, $_tmp) : smarty_modifier_strip($_tmp)) != ''): ?>Image Credit: <?php echo ((is_array($_tmp=$this->_tpl_vars['article_info']['image_credit'])) ? $this->_run_mod_handler('cat', true, $_tmp, "\r\n") : smarty_modifier_cat($_tmp, "\r\n"));  endif; ?>
<?php if (((is_array($_tmp=$this->_tpl_vars['article_info']['image_caption'])) ? $this->_run_mod_handler('strip', true, $_tmp) : smarty_modifier_strip($_tmp)) != ''): ?>Image Caption: <?php echo ((is_array($_tmp=$this->_tpl_vars['article_info']['image_caption'])) ? $this->_run_mod_handler('cat', true, $_tmp, "\r\n") : smarty_modifier_cat($_tmp, "\r\n"));  endif; ?>
<?php if (((is_array($_tmp=$this->_tpl_vars['article_info']['blurb'])) ? $this->_run_mod_handler('strip', true, $_tmp) : smarty_modifier_strip($_tmp)) != ''): ?>Blurb: <?php echo ((is_array($_tmp=$this->_tpl_vars['article_info']['blurb'])) ? $this->_run_mod_handler('cat', true, $_tmp, "\r\n") : smarty_modifier_cat($_tmp, "\r\n"));  endif; ?>
<?php if (((is_array($_tmp=$this->_tpl_vars['article_info']['meta_description'])) ? $this->_run_mod_handler('strip', true, $_tmp) : smarty_modifier_strip($_tmp)) != ''): ?>Meta description: <?php echo ((is_array($_tmp=$this->_tpl_vars['article_info']['meta_description'])) ? $this->_run_mod_handler('cat', true, $_tmp, "\r\n") : smarty_modifier_cat($_tmp, "\r\n"));  endif; ?>
<?php if (((is_array($_tmp=$this->_tpl_vars['article_info']['category_id'])) ? $this->_run_mod_handler('strip', true, $_tmp) : smarty_modifier_strip($_tmp)) != ''): ?>Category: <?php echo ((is_array($_tmp=$this->_tpl_vars['article_info']['category_id'])) ? $this->_run_mod_handler('cat', true, $_tmp, "\r\n") : smarty_modifier_cat($_tmp, "\r\n"));  endif; ?>
<?php endif; ?>
Article content: <?php echo "\r\n"; ?>

<?php echo ((is_array($_tmp=$this->_tpl_vars['article_info']['body'])) ? $this->_run_mod_handler('cat', true, $_tmp, "\r\n") : smarty_modifier_cat($_tmp, "\r\n")); ?>